baseURL = "https://www.cariad.games/"
languageCode = "en-gb"
theme = "cg"
title = "cariad.games"

[params]
  [params.author]
    emoji = "ğŸ‘©â€ğŸ’»"
    fediverse = "@cariad@queer.garden"
    name = "Cariad Eccleston"
    url = "https://queer.garden/@cariad"
